// <auto-generated />
using BookShopping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShopping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240509121410_SeedValuestoUserTable")]
    partial class SeedValuestoUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookShopping.Models.Book_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("re_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reg_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sadasivam",
                            email = "sadasivam@gmail.com",
                            password = "sada",
                            re_password = "sada"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Abcd",
                            email = "abcd@gmail.com",
                            password = "abcd",
                            re_password = "abcd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
